'''
PLAYER GOAL: GET CLOSER TO A TOTAL VALUE OF 21 THAN THE DEALER DOES

POSSIBLE ACTIONS:
    1. Hit - Receive another card
    2. Stay -  Stop receiving cards

Ignore the following actions -- Insurance, Split, Double Down

AFTER PLAYER TURN:
    IF PLAYER IS UNDER 21, DEALER THEN HITS UNTIL THEY EITHER BEAT THE PLAYER OR
    DEALER BUSTS(OVER 21)

POSSIBLE GAME END SCENARIOS:
    - PLAYER CONTINUES TO HITS AND GOES OVER 21
    - COMPUTER DEAL BEATS THE PLAYER BY HAVING A HIGHER SUM THAN PLAYER & IS UNDER 21
    - PLAYER WINS AFTER COMPUTER DEALER'S TURN

SPECIAL RULES:
    - FACES CARD = 10
    - ACES = 1 OR 11 WHICHEVER VALUE IS PREFERABLE TO THE PLAYER

'''
